- id: update-translations
  name: update translations
  description: Ensures all the ts files are up to date.
  entry: qpdt transup --check-changes
  language: system
  files: \.(py|ui)$
  require_serial: true
  pass_filenames: false
