name: Create draft release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version number without "v" tag prefix (i.e. "1.0.0")

jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nlsfi/python-repo-draft-release-action@vea46c6e11789b863fdd1662748f469fc5fb421d4 # v1.0.0
        with:
          version: ${{ inputs.version }}
          version_file: src/qgis_plugin_dev_tools/__init__.py
